// ---------------------------------------------------------------------------
// DRAFT ROOM — the server logic behind /api/draft, /api/draft-pick and
// /api/draft-admin. Every write happens inside the draft lock and re-reads the
// latest document first, so two rapid submissions can't both land, and every
// time the server stamps comes from the SERVER's clock.
//
// Auth (reusing the site's pattern, never modifying the RSVP code):
//   commissioner — your RSVP admin key (x-admin-key), checked by the RSVP API's
//                  own isAdminKey()
//   captains     — one random key each, generated by the commissioner console and
//                  kept only in Redis (draft:2027:<mode> → keys); never returned
//                  by the public GET
// ---------------------------------------------------------------------------
import crypto from 'node:crypto';
import { isAdminKey } from './rsvp-api.js';
import { slugify } from './rsvp-shared.js';
import { players as sitePlayers } from './data.js';
import * as store from './draft-store.js';
import { loadLineups, saveLineups } from './lineup-store.js';
import { emptyLineups } from './matchcentre-shared.js';
import { MODES, PICK_MS, REVEAL_MS, SLAM_MS, TEAM_COLOURS, emptyDraft, snakeOrder, picksFor, rosters, available, phaseAt } from './draft-shared.js';

export class DraftError extends Error {
  constructor(message, status = 400) { super(message); this.status = status; }
}

const nameOf = (id) => sitePlayers.find((p) => p.id === id)?.name ?? id;
const validIds = () => new Set(sitePlayers.map((p) => p.id));
// A local test run can shorten the clock (DRAFT_PICK_SECONDS); production always
// uses the full 2:00 — the override is ignored on Vercel.
const pickMsFor = (env) => (!env.VERCEL && Number(env.DRAFT_PICK_SECONDS) > 0 ? Number(env.DRAFT_PICK_SECONDS) * 1000 : PICK_MS);
const newKey = () => crypto.randomBytes(24).toString('base64url');   // 32 characters
const keyMatches = (a, b) => typeof a === 'string' && typeof b === 'string' && a.length === b.length && crypto.timingSafeEqual(Buffer.from(a), Buffer.from(b));

function requireAdmin(key, env) {
  if (!env.RSVP_ADMIN_KEY) throw new DraftError('Admin key not set up yet (RSVP_ADMIN_KEY).', 503);
  if (!isAdminKey(key, env)) throw new DraftError('Wrong or missing admin key.', 401);
}

// Fire the deploy hook (same env var the RSVPs use) so the site rebuilds with
// the finalised teams. Best-effort: never throws.
async function triggerRebuild(env) {
  const hook = (env.RSVP_DEPLOY_HOOK_URL || '').trim().replace(/^["']|["']$/g, '');
  if (!hook) return 'no-hook';
  try { const r = await fetch(hook, { method: 'POST', signal: AbortSignal.timeout(8000) }); return r.ok ? 'triggered' : `hook-http-${r.status}`; }
  catch (e) { console.error('Draft: deploy hook failed', e); return 'hook-failed'; }
}

async function current(env) {
  const mode = await store.loadMode(env);
  const doc = (await store.loadDraft(mode, env)) || emptyDraft(mode);
  return { mode, doc };
}

/** GET /api/draft — the public state (no keys) + the server's clock. */
export async function readDraft({ env = process.env } = {}) {
  const { mode, doc } = await current(env);
  return { ok: true, mode, draft: doc, serverNow: Date.now() };
}

// ---- captain: lock in a pick ----------------------------------------------
/** Which side a captain key belongs to in the active draft (or null). */
export async function sideForKey(key, env = process.env) {
  const mode = await store.loadMode(env);
  const keys = await store.loadKeys(mode, env);
  return ['A', 'B'].find((s) => keys[s] && keyMatches(key, keys[s])) || null;
}

export async function captainState(key, { env = process.env } = {}) {
  const side = await sideForKey(key, env);
  if (!side) throw new DraftError('That captain link isn’t valid for the current draft.', 401);
  return { ...(await readDraft({ env })), side };
}

export async function submitPick(key, body, { env = process.env } = {}) {
  const pickNo = Number(body?.pickNo);
  const playerId = String(body?.playerId || '');
  return store.withDraftLock(async () => {
    const { mode, doc } = await current(env);
    const keys = await store.loadKeys(mode, env);
    const side = ['A', 'B'].find((s) => keys[s] && keyMatches(key, keys[s]));
    if (!side) throw new DraftError('That captain link isn’t valid for the current draft.', 401);
    // Already made? The same captain re-sending the same player (a double tap, a
    // retry after a dropped reply) is a harmless no-op; anything else is refused.
    const made = doc.picks.find((p) => p.n === pickNo);
    if (made) {
      if (made.side === side && made.playerId === playerId) return { ok: true, repeat: true, mode, draft: doc, serverNow: Date.now() };
      throw new DraftError('That pick is already in.', 409);
    }
    const now = Date.now();
    const ph = phaseAt(doc, now);
    if (!['clock', 'overtime'].includes(ph.phase)) throw new DraftError(ph.phase === 'paused' ? 'The draft is paused.' : 'Not open for a pick right now.', 409);
    if (ph.pickNo !== pickNo) throw new DraftError(`It's pick ${ph.pickNo}, not ${pickNo}.`, 409);
    if (ph.side !== side) throw new DraftError('You’re not on the clock.', 409);
    if (!available(doc).includes(playerId)) throw new DraftError('That player isn’t available.', 409);
    const last = pickNo === doc.order.length;
    const next = {
      ...doc, rev: doc.rev + 1,
      picks: [...doc.picks, { n: pickNo, side, playerId, lockedAt: now, clockMs: now - doc.clock.startsAt }],
      reveal: { pickNo, side, playerId, lockedAt: now, revealAt: now + REVEAL_MS, doneAt: now + REVEAL_MS + SLAM_MS },
      clock: last ? null : { pickNo: pickNo + 1, startsAt: now + REVEAL_MS + SLAM_MS },
      status: last ? 'complete' : 'running',
    };
    await store.saveDraft(mode, next, env);
    return { ok: true, mode, draft: next, serverNow: Date.now() };
  }, env);
}

// ---- commissioner ------------------------------------------------------------
/** GET (admin): the state + the captain links' keys + the colour palette. */
export async function readAdmin(key, { env = process.env } = {}) {
  requireAdmin(key, env);
  const { mode, doc } = await current(env);
  return { ok: true, mode, draft: doc, keys: await store.loadKeys(mode, env), colours: TEAM_COLOURS, serverNow: Date.now() };
}

export async function adminAction(key, body, { env = process.env } = {}) {
  requireAdmin(key, env);
  const action = String(body?.action || '');
  return store.withDraftLock(async () => {
    if (action === 'mode') {
      const mode = body.mode;
      if (!MODES.includes(mode)) throw new DraftError('Mode must be real or mock.');
      await store.saveMode(mode, env);
      return readAdmin(key, { env });
    }
    const { mode, doc } = await current(env);
    const now = Date.now();
    const save = async (next, extra = {}) => { const d = { ...next, rev: doc.rev + 1 }; await store.saveDraft(mode, d, env); return { ...(await readAdmin(key, { env })), ...extra }; };

    switch (action) {
      case 'setup': {
        if (doc.status !== 'setup') throw new DraftError('Setup is locked once the draft has started (RESET to change it).', 409);
        const ids = validIds();
        const participants = [...new Set((body.participants || []).map(String))];
        for (const id of participants) if (!ids.has(id)) throw new DraftError(`Unknown player "${id}".`);
        const captains = { A: body.captains?.A || null, B: body.captains?.B || null };
        for (const s of ['A', 'B']) if (captains[s] && !participants.includes(captains[s])) throw new DraftError('Both captains must be in the draft.');
        if (captains.A && captains.A === captains.B) throw new DraftError('Pick two different captains.');
        const firstPick = body.firstPick === 'B' ? 'B' : 'A';
        return save({ ...doc, participants, captains, firstPick });
      }
      case 'keys': {
        const side = body.side;
        const keys = await store.loadKeys(mode, env);
        for (const s of (side === 'A' || side === 'B') ? [side] : ['A', 'B']) keys[s] = newKey();   // regenerating kills the old link
        await store.saveKeys(mode, keys, env);
        return readAdmin(key, { env });
      }
      case 'start': {
        if (doc.status !== 'setup') throw new DraftError('The draft has already started.', 409);
        const n = doc.participants.length;
        if (n < 4 || n % 2) throw new DraftError('Start needs an EVEN number of players (4 or more), captains included.');
        if (!doc.captains.A || !doc.captains.B) throw new DraftError('Set both captains first.');
        const keys = await store.loadKeys(mode, env);
        if (!keys.A || !keys.B) throw new DraftError('Generate the captain links first.');
        const order = snakeOrder(picksFor(n), doc.firstPick);
        return save({ ...doc, status: 'running', order, picks: [], reveal: null, pickMs: pickMsFor(env), startedAt: now, clock: { pickNo: 1, startsAt: now } });
      }
      case 'pause': {
        if (doc.status !== 'running') throw new DraftError('Only a running draft can be paused.', 409);
        return save({ ...doc, status: 'paused', pausedAt: now });
      }
      case 'resume': {
        if (doc.status !== 'paused') throw new DraftError('The draft isn’t paused.', 409);
        // Shift every pending timestamp by the pause, so the clock (and any reveal
        // that was mid-flight) carries on exactly where it stopped.
        const d = now - (doc.pausedAt ?? now);
        const clock = doc.clock ? { ...doc.clock, startsAt: doc.clock.startsAt + d } : null;
        const reveal = doc.reveal ? { ...doc.reveal, revealAt: doc.reveal.revealAt + d, doneAt: doc.reveal.doneAt + d } : null;
        return save({ ...doc, status: doc.picks.length === doc.order.length ? 'complete' : 'running', pausedAt: null, clock, reveal });
      }
      case 'undo': {
        if (!['running', 'paused', 'complete'].includes(doc.status) || !doc.picks.length) throw new DraftError('Nothing to undo.', 409);
        const lastPick = doc.picks[doc.picks.length - 1];
        // The player goes back in the pool; the draft pauses with that captain back
        // on the clock, which restarts at a full 2:00 on RESUME.
        return save({ ...doc, status: 'paused', pausedAt: now, picks: doc.picks.slice(0, -1), reveal: null, clock: { pickNo: lastPick.n, startsAt: now } },
          { undone: { pickNo: lastPick.n, playerId: lastPick.playerId, name: nameOf(lastPick.playerId) } });
      }
      case 'reset': {
        if (String(body.confirm || '').trim().toUpperCase() !== 'RESET') throw new DraftError('Type RESET to confirm.');
        if (doc.status === 'finalised' && mode === 'real' && body.unfinalise !== true) throw new DraftError('This draft is finalised. Resetting it won’t undo the rosters already written — tick “I understand” to reset anyway.', 409);
        // Keep the setup (players, captains, who picks first) so a rehearsal can go again.
        return save({ ...emptyDraft(mode), participants: doc.participants, captains: doc.captains, firstPick: doc.firstPick });
      }
      case 'finalise': return finalise(doc, mode, body, key, env, save);
      default: throw new DraftError(`Unknown action "${action}".`);
    }
  }, env);
}

// ---- finalise ---------------------------------------------------------------
async function finalise(doc, mode, body, key, env, save) {
  if (doc.status !== 'complete') throw new DraftError('Finalise once every pick is in.', 409);
  const r = rosters(doc);
  const teams = {};
  const palette = new Map(TEAM_COLOURS.map((c) => [c.id, c]));
  for (const s of ['A', 'B']) {
    const captain = doc.captains[s];
    const name = String(body.teams?.[s]?.name || '').replace(/\s+/g, ' ').trim() || `Team ${nameOf(captain).split(' ').pop()}`;
    if (name.length > 40) throw new DraftError('Team names must be 40 characters or fewer.');
    const colour = palette.get(body.teams?.[s]?.color);
    if (!colour) throw new DraftError('Pick a colour for each team from the palette.');
    teams[s] = { name, color: colour.hex, colorId: colour.id, captainId: captain, playerIds: r[s] };
  }
  if (teams.A.colorId === teams.B.colorId) throw new DraftError('Give the two teams different colours.');
  // ids: kebab-case from the name, never clashing with each other or an existing team
  const taken = new Set(['woodpeckers', 'silver-spoons']);
  for (const s of ['A', 'B']) {
    let id = slugify(teams[s].name) || `team-${s.toLowerCase()}`;
    if (taken.has(id)) id = `${id}-2027`;
    taken.add(id); teams[s].id = id;
  }

  // MOCK: a dry run. The mock draft itself finalises (so the board rehearses its
  // final screen in the chosen names and colours), but nothing outside the mock
  // is written: no lineups, no rebuild. RESET brings it back.
  if (mode === 'mock') {
    const { doc: lu } = await loadLineups(2027, env);
    const out = await save({ ...doc, status: 'finalised', finalisedAt: Date.now(), teams: { A: teams.A, B: teams.B } });
    return { ...out, rehearsal: true, wouldWrite: { teams, clearedSlots: conflicts(lu, r).length } };
  }

  // 1. Match Centre: the rosters go straight onto the lineups document, and any
  //    slot that breaks them is cleared (listed back to the commissioner).
  const { doc: lu0 } = await loadLineups(2027, env);
  const lu = lu0 ? structuredClone(lu0) : emptyLineups(doc.tournamentId);
  const cleared = conflicts(lu, r);
  for (const c of cleared) lu.rounds[c.round][c.match][c.side][c.slot] = null;
  const saved = { ...lu, rosters: { A: r.A, B: r.B }, rev: (lu.rev || 0) + 1, updatedAt: new Date().toISOString() };
  await saveLineups(2027, saved, env);
  // 2. The draft document itself (the build reads this — scripts/pull-draft.mjs).
  const out = await save({ ...doc, status: 'finalised', finalisedAt: Date.now(), teams: { A: teams.A, B: teams.B } });
  // 3. Rebuild the site so the 2027 page shows the real teams.
  const rebuild = await triggerRebuild(env);
  return { ...out, finalised: true, clearedSlots: cleared.map((c) => ({ ...c, name: nameOf(c.playerId) })), rebuild };
}

/** Lineup slots holding someone who isn't on that side's drafted roster. */
function conflicts(lu, r) {
  const out = [];
  for (const [round, ms] of Object.entries(lu?.rounds || {})) {
    for (const [match, sides] of Object.entries(ms)) {
      for (const side of ['A', 'B']) (sides[side] || []).forEach((id, slot) => { if (id && !r[side].includes(id)) out.push({ round, match, side, slot, playerId: id }); });
    }
  }
  return out;
}
